/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ArquivosRouteImport } from './routes/arquivos'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as FerramentasWhatsappRouteImport } from './routes/ferramentas.whatsapp'
import { Route as FerramentasExcelRouteImport } from './routes/ferramentas.excel'
import { Route as FerramentasEmailsRouteImport } from './routes/ferramentas.emails'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiGmailWebhookRouteImport } from './routes/api/gmail-webhook'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail-callback'

const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosRoute = ArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasWhatsappRoute = FerramentasWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasExcelRoute = FerramentasExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasEmailsRoute = FerramentasEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => FerramentasRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailWebhookRoute = ApiGmailWebhookRouteImport.update({
  id: '/api/gmail-webhook',
  path: '/api/gmail-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail-callback',
  path: '/api/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anotacoes': typeof AnotacoesRoute
  '/arquivos': typeof ArquivosRoute
  '/config': typeof ConfigRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/gmail-callback': typeof ApiGmailCallbackRoute
  '/api/gmail-webhook': typeof ApiGmailWebhookRoute
  '/api/version': typeof ApiVersionRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/ferramentas/emails': typeof FerramentasEmailsRoute
  '/ferramentas/excel': typeof FerramentasExcelRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/ferramentas/': typeof FerramentasIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anotacoes': typeof AnotacoesRoute
  '/arquivos': typeof ArquivosRoute
  '/config': typeof ConfigRoute
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/gmail-callback': typeof ApiGmailCallbackRoute
  '/api/gmail-webhook': typeof ApiGmailWebhookRoute
  '/api/version': typeof ApiVersionRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/ferramentas/emails': typeof FerramentasEmailsRoute
  '/ferramentas/excel': typeof FerramentasExcelRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/ferramentas': typeof FerramentasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/anotacoes': typeof AnotacoesRoute
  '/arquivos': typeof ArquivosRoute
  '/config': typeof ConfigRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/usuarios': typeof UsuariosRoute
  '/api/gmail-callback': typeof ApiGmailCallbackRoute
  '/api/gmail-webhook': typeof ApiGmailWebhookRoute
  '/api/version': typeof ApiVersionRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/ferramentas/emails': typeof FerramentasEmailsRoute
  '/ferramentas/excel': typeof FerramentasExcelRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/ferramentas/': typeof FerramentasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/anotacoes'
    | '/arquivos'
    | '/config'
    | '/ferramentas'
    | '/login'
    | '/projetos'
    | '/usuarios'
    | '/api/gmail-callback'
    | '/api/gmail-webhook'
    | '/api/version'
    | '/api/whatsapp-webhook'
    | '/ferramentas/emails'
    | '/ferramentas/excel'
    | '/ferramentas/whatsapp'
    | '/ferramentas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/anotacoes'
    | '/arquivos'
    | '/config'
    | '/login'
    | '/projetos'
    | '/usuarios'
    | '/api/gmail-callback'
    | '/api/gmail-webhook'
    | '/api/version'
    | '/api/whatsapp-webhook'
    | '/ferramentas/emails'
    | '/ferramentas/excel'
    | '/ferramentas/whatsapp'
    | '/ferramentas'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/anotacoes'
    | '/arquivos'
    | '/config'
    | '/ferramentas'
    | '/login'
    | '/projetos'
    | '/usuarios'
    | '/api/gmail-callback'
    | '/api/gmail-webhook'
    | '/api/version'
    | '/api/whatsapp-webhook'
    | '/ferramentas/emails'
    | '/ferramentas/excel'
    | '/ferramentas/whatsapp'
    | '/ferramentas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  AnotacoesRoute: typeof AnotacoesRoute
  ArquivosRoute: typeof ArquivosRoute
  ConfigRoute: typeof ConfigRoute
  FerramentasRoute: typeof FerramentasRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjetosRoute: typeof ProjetosRoute
  UsuariosRoute: typeof UsuariosRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  ApiGmailWebhookRoute: typeof ApiGmailWebhookRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos': {
      id: '/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof ArquivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/whatsapp': {
      id: '/ferramentas/whatsapp'
      path: '/whatsapp'
      fullPath: '/ferramentas/whatsapp'
      preLoaderRoute: typeof FerramentasWhatsappRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/excel': {
      id: '/ferramentas/excel'
      path: '/excel'
      fullPath: '/ferramentas/excel'
      preLoaderRoute: typeof FerramentasExcelRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/emails': {
      id: '/ferramentas/emails'
      path: '/emails'
      fullPath: '/ferramentas/emails'
      preLoaderRoute: typeof FerramentasEmailsRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-webhook': {
      id: '/api/gmail-webhook'
      path: '/api/gmail-webhook'
      fullPath: '/api/gmail-webhook'
      preLoaderRoute: typeof ApiGmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-callback': {
      id: '/api/gmail-callback'
      path: '/api/gmail-callback'
      fullPath: '/api/gmail-callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface FerramentasRouteChildren {
  FerramentasEmailsRoute: typeof FerramentasEmailsRoute
  FerramentasExcelRoute: typeof FerramentasExcelRoute
  FerramentasWhatsappRoute: typeof FerramentasWhatsappRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
}

const FerramentasRouteChildren: FerramentasRouteChildren = {
  FerramentasEmailsRoute: FerramentasEmailsRoute,
  FerramentasExcelRoute: FerramentasExcelRoute,
  FerramentasWhatsappRoute: FerramentasWhatsappRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
}

const FerramentasRouteWithChildren = FerramentasRoute._addFileChildren(
  FerramentasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  AnotacoesRoute: AnotacoesRoute,
  ArquivosRoute: ArquivosRoute,
  ConfigRoute: ConfigRoute,
  FerramentasRoute: FerramentasRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjetosRoute: ProjetosRoute,
  UsuariosRoute: UsuariosRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  ApiGmailWebhookRoute: ApiGmailWebhookRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
