/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FerramentasRouteImport } from './routes/ferramentas'
import { Route as DebugUserIdRouteImport } from './routes/debug-user-id'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CrmRouteImport } from './routes/crm'
import { Route as ConfigRouteImport } from './routes/config'
import { Route as ArquivosRouteImport } from './routes/arquivos'
import { Route as AnotacoesRouteImport } from './routes/anotacoes'
import { Route as AgendaRouteImport } from './routes/agenda'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as FerramentasIndexRouteImport } from './routes/ferramentas.index'
import { Route as ConfigIndexRouteImport } from './routes/config.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as FerramentasWhatsappRouteImport } from './routes/ferramentas.whatsapp'
import { Route as FerramentasExcelRouteImport } from './routes/ferramentas.excel'
import { Route as FerramentasEmailsRouteImport } from './routes/ferramentas.emails'
import { Route as CrmTarefasRouteImport } from './routes/crm.tarefas'
import { Route as CrmServicosRouteImport } from './routes/crm.servicos'
import { Route as CrmPipelineRouteImport } from './routes/crm.pipeline'
import { Route as CrmPecasRouteImport } from './routes/crm.pecas'
import { Route as CrmPagamentosRouteImport } from './routes/crm.pagamentos'
import { Route as CrmOsRouteImport } from './routes/crm.os'
import { Route as CrmOrcamentosRouteImport } from './routes/crm.orcamentos'
import { Route as CrmContratosRouteImport } from './routes/crm.contratos'
import { Route as CrmClientesRouteImport } from './routes/crm.clientes'
import { Route as CrmChamadosRouteImport } from './routes/crm.chamados'
import { Route as ConfigPermissionsRouteImport } from './routes/config.permissions'
import { Route as ApiWhatsappWebhookRouteImport } from './routes/api/whatsapp-webhook'
import { Route as ApiVersionRouteImport } from './routes/api/version'
import { Route as ApiGmailWebhookRouteImport } from './routes/api/gmail-webhook'
import { Route as ApiGmailCallbackRouteImport } from './routes/api/gmail-callback'
import { Route as ApiDeleteGmailTokenRouteImport } from './routes/api/delete-gmail-token'
import { Route as ApiDebugProcessPipelineRouteImport } from './routes/api/debug-process-pipeline'
import { Route as ApiDebugProcessEmailRouteImport } from './routes/api/debug-process-email'
import { Route as ApiDebugInterpretEmailRouteImport } from './routes/api/debug-interpret-email'
import { Route as ApiDebugGmailTokenRouteImport } from './routes/api/debug-gmail-token'
import { Route as ApiDebugFetchEmailsRouteImport } from './routes/api/debug-fetch-emails'
import { Route as AdminSetupRouteImport } from './routes/admin.setup'
import { Route as AdminOperatorIdRouteImport } from './routes/admin.$operatorId'
import { Route as CrmOsIndexRouteImport } from './routes/crm.os.index'
import { Route as CrmOrcamentosIndexRouteImport } from './routes/crm.orcamentos.index'
import { Route as CrmContratosIndexRouteImport } from './routes/crm.contratos.index'
import { Route as CrmClientesIndexRouteImport } from './routes/crm.clientes.index'
import { Route as CrmChamadosIndexRouteImport } from './routes/crm.chamados.index'
import { Route as OrcamentoApproveTokenRouteImport } from './routes/orcamento.approve.$token'
import { Route as CrmOrcamentosIdRouteImport } from './routes/crm.orcamentos.$id'
import { Route as CrmContratosNovoRouteImport } from './routes/crm.contratos.novo'
import { Route as CrmContratosModelosRouteImport } from './routes/crm.contratos.modelos'
import { Route as CrmClientesIdRouteImport } from './routes/crm.clientes.$id'
import { Route as CrmChamadosIdRouteImport } from './routes/crm.chamados.$id'
import { Route as CrmOrcamentosEditarIdRouteImport } from './routes/crm.orcamentos.editar.$id'

const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasRoute = FerramentasRouteImport.update({
  id: '/ferramentas',
  path: '/ferramentas',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugUserIdRoute = DebugUserIdRouteImport.update({
  id: '/debug-user-id',
  path: '/debug-user-id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmRoute = CrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigRoute = ConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ArquivosRoute = ArquivosRouteImport.update({
  id: '/arquivos',
  path: '/arquivos',
  getParentRoute: () => rootRouteImport,
} as any)
const AnotacoesRoute = AnotacoesRouteImport.update({
  id: '/anotacoes',
  path: '/anotacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaRoute = AgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const FerramentasIndexRoute = FerramentasIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => FerramentasRoute,
} as any)
const ConfigIndexRoute = ConfigIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ConfigRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const FerramentasWhatsappRoute = FerramentasWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasExcelRoute = FerramentasExcelRouteImport.update({
  id: '/excel',
  path: '/excel',
  getParentRoute: () => FerramentasRoute,
} as any)
const FerramentasEmailsRoute = FerramentasEmailsRouteImport.update({
  id: '/emails',
  path: '/emails',
  getParentRoute: () => FerramentasRoute,
} as any)
const CrmTarefasRoute = CrmTarefasRouteImport.update({
  id: '/tarefas',
  path: '/tarefas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmServicosRoute = CrmServicosRouteImport.update({
  id: '/servicos',
  path: '/servicos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPipelineRoute = CrmPipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPecasRoute = CrmPecasRouteImport.update({
  id: '/pecas',
  path: '/pecas',
  getParentRoute: () => CrmRoute,
} as any)
const CrmPagamentosRoute = CrmPagamentosRouteImport.update({
  id: '/pagamentos',
  path: '/pagamentos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOsRoute = CrmOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => CrmRoute,
} as any)
const CrmOrcamentosRoute = CrmOrcamentosRouteImport.update({
  id: '/orcamentos',
  path: '/orcamentos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmContratosRoute = CrmContratosRouteImport.update({
  id: '/contratos',
  path: '/contratos',
  getParentRoute: () => CrmRoute,
} as any)
const CrmClientesRoute = CrmClientesRouteImport.update({
  id: '/clientes',
  path: '/clientes',
  getParentRoute: () => CrmRoute,
} as any)
const CrmChamadosRoute = CrmChamadosRouteImport.update({
  id: '/chamados',
  path: '/chamados',
  getParentRoute: () => CrmRoute,
} as any)
const ConfigPermissionsRoute = ConfigPermissionsRouteImport.update({
  id: '/permissions',
  path: '/permissions',
  getParentRoute: () => ConfigRoute,
} as any)
const ApiWhatsappWebhookRoute = ApiWhatsappWebhookRouteImport.update({
  id: '/api/whatsapp-webhook',
  path: '/api/whatsapp-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiVersionRoute = ApiVersionRouteImport.update({
  id: '/api/version',
  path: '/api/version',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailWebhookRoute = ApiGmailWebhookRouteImport.update({
  id: '/api/gmail-webhook',
  path: '/api/gmail-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGmailCallbackRoute = ApiGmailCallbackRouteImport.update({
  id: '/api/gmail-callback',
  path: '/api/gmail-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDeleteGmailTokenRoute = ApiDeleteGmailTokenRouteImport.update({
  id: '/api/delete-gmail-token',
  path: '/api/delete-gmail-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugProcessPipelineRoute = ApiDebugProcessPipelineRouteImport.update({
  id: '/api/debug-process-pipeline',
  path: '/api/debug-process-pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugProcessEmailRoute = ApiDebugProcessEmailRouteImport.update({
  id: '/api/debug-process-email',
  path: '/api/debug-process-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugInterpretEmailRoute = ApiDebugInterpretEmailRouteImport.update({
  id: '/api/debug-interpret-email',
  path: '/api/debug-interpret-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugGmailTokenRoute = ApiDebugGmailTokenRouteImport.update({
  id: '/api/debug-gmail-token',
  path: '/api/debug-gmail-token',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDebugFetchEmailsRoute = ApiDebugFetchEmailsRouteImport.update({
  id: '/api/debug-fetch-emails',
  path: '/api/debug-fetch-emails',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSetupRoute = AdminSetupRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOperatorIdRoute = AdminOperatorIdRouteImport.update({
  id: '/$operatorId',
  path: '/$operatorId',
  getParentRoute: () => AdminRoute,
} as any)
const CrmOsIndexRoute = CrmOsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmOsRoute,
} as any)
const CrmOrcamentosIndexRoute = CrmOrcamentosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmOrcamentosRoute,
} as any)
const CrmContratosIndexRoute = CrmContratosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmContratosRoute,
} as any)
const CrmClientesIndexRoute = CrmClientesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmClientesRoute,
} as any)
const CrmChamadosIndexRoute = CrmChamadosIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CrmChamadosRoute,
} as any)
const OrcamentoApproveTokenRoute = OrcamentoApproveTokenRouteImport.update({
  id: '/orcamento/approve/$token',
  path: '/orcamento/approve/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const CrmOrcamentosIdRoute = CrmOrcamentosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmOrcamentosRoute,
} as any)
const CrmContratosNovoRoute = CrmContratosNovoRouteImport.update({
  id: '/novo',
  path: '/novo',
  getParentRoute: () => CrmContratosRoute,
} as any)
const CrmContratosModelosRoute = CrmContratosModelosRouteImport.update({
  id: '/modelos',
  path: '/modelos',
  getParentRoute: () => CrmContratosRoute,
} as any)
const CrmClientesIdRoute = CrmClientesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmClientesRoute,
} as any)
const CrmChamadosIdRoute = CrmChamadosIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => CrmChamadosRoute,
} as any)
const CrmOrcamentosEditarIdRoute = CrmOrcamentosEditarIdRouteImport.update({
  id: '/editar/$id',
  path: '/editar/$id',
  getParentRoute: () => CrmOrcamentosRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/anotacoes': typeof AnotacoesRoute
  '/arquivos': typeof ArquivosRoute
  '/config': typeof ConfigRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/debug-user-id': typeof DebugUserIdRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/admin/$operatorId': typeof AdminOperatorIdRoute
  '/admin/setup': typeof AdminSetupRoute
  '/api/debug-fetch-emails': typeof ApiDebugFetchEmailsRoute
  '/api/debug-gmail-token': typeof ApiDebugGmailTokenRoute
  '/api/debug-interpret-email': typeof ApiDebugInterpretEmailRoute
  '/api/debug-process-email': typeof ApiDebugProcessEmailRoute
  '/api/debug-process-pipeline': typeof ApiDebugProcessPipelineRoute
  '/api/delete-gmail-token': typeof ApiDeleteGmailTokenRoute
  '/api/gmail-callback': typeof ApiGmailCallbackRoute
  '/api/gmail-webhook': typeof ApiGmailWebhookRoute
  '/api/version': typeof ApiVersionRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/config/permissions': typeof ConfigPermissionsRoute
  '/crm/chamados': typeof CrmChamadosRouteWithChildren
  '/crm/clientes': typeof CrmClientesRouteWithChildren
  '/crm/contratos': typeof CrmContratosRouteWithChildren
  '/crm/orcamentos': typeof CrmOrcamentosRouteWithChildren
  '/crm/os': typeof CrmOsRouteWithChildren
  '/crm/pagamentos': typeof CrmPagamentosRoute
  '/crm/pecas': typeof CrmPecasRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/servicos': typeof CrmServicosRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/ferramentas/emails': typeof FerramentasEmailsRoute
  '/ferramentas/excel': typeof FerramentasExcelRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/crm/chamados/$id': typeof CrmChamadosIdRoute
  '/crm/clientes/$id': typeof CrmClientesIdRoute
  '/crm/contratos/modelos': typeof CrmContratosModelosRoute
  '/crm/contratos/novo': typeof CrmContratosNovoRoute
  '/crm/orcamentos/$id': typeof CrmOrcamentosIdRoute
  '/orcamento/approve/$token': typeof OrcamentoApproveTokenRoute
  '/crm/chamados/': typeof CrmChamadosIndexRoute
  '/crm/clientes/': typeof CrmClientesIndexRoute
  '/crm/contratos/': typeof CrmContratosIndexRoute
  '/crm/orcamentos/': typeof CrmOrcamentosIndexRoute
  '/crm/os/': typeof CrmOsIndexRoute
  '/crm/orcamentos/editar/$id': typeof CrmOrcamentosEditarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agenda': typeof AgendaRoute
  '/anotacoes': typeof AnotacoesRoute
  '/arquivos': typeof ArquivosRoute
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/debug-user-id': typeof DebugUserIdRoute
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/admin/$operatorId': typeof AdminOperatorIdRoute
  '/admin/setup': typeof AdminSetupRoute
  '/api/debug-fetch-emails': typeof ApiDebugFetchEmailsRoute
  '/api/debug-gmail-token': typeof ApiDebugGmailTokenRoute
  '/api/debug-interpret-email': typeof ApiDebugInterpretEmailRoute
  '/api/debug-process-email': typeof ApiDebugProcessEmailRoute
  '/api/debug-process-pipeline': typeof ApiDebugProcessPipelineRoute
  '/api/delete-gmail-token': typeof ApiDeleteGmailTokenRoute
  '/api/gmail-callback': typeof ApiGmailCallbackRoute
  '/api/gmail-webhook': typeof ApiGmailWebhookRoute
  '/api/version': typeof ApiVersionRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/config/permissions': typeof ConfigPermissionsRoute
  '/crm/pagamentos': typeof CrmPagamentosRoute
  '/crm/pecas': typeof CrmPecasRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/servicos': typeof CrmServicosRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/ferramentas/emails': typeof FerramentasEmailsRoute
  '/ferramentas/excel': typeof FerramentasExcelRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/admin': typeof AdminIndexRoute
  '/config': typeof ConfigIndexRoute
  '/ferramentas': typeof FerramentasIndexRoute
  '/crm/chamados/$id': typeof CrmChamadosIdRoute
  '/crm/clientes/$id': typeof CrmClientesIdRoute
  '/crm/contratos/modelos': typeof CrmContratosModelosRoute
  '/crm/contratos/novo': typeof CrmContratosNovoRoute
  '/crm/orcamentos/$id': typeof CrmOrcamentosIdRoute
  '/orcamento/approve/$token': typeof OrcamentoApproveTokenRoute
  '/crm/chamados': typeof CrmChamadosIndexRoute
  '/crm/clientes': typeof CrmClientesIndexRoute
  '/crm/contratos': typeof CrmContratosIndexRoute
  '/crm/orcamentos': typeof CrmOrcamentosIndexRoute
  '/crm/os': typeof CrmOsIndexRoute
  '/crm/orcamentos/editar/$id': typeof CrmOrcamentosEditarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/agenda': typeof AgendaRoute
  '/anotacoes': typeof AnotacoesRoute
  '/arquivos': typeof ArquivosRoute
  '/config': typeof ConfigRouteWithChildren
  '/crm': typeof CrmRouteWithChildren
  '/dashboard': typeof DashboardRoute
  '/debug-user-id': typeof DebugUserIdRoute
  '/ferramentas': typeof FerramentasRouteWithChildren
  '/login': typeof LoginRoute
  '/projetos': typeof ProjetosRoute
  '/admin/$operatorId': typeof AdminOperatorIdRoute
  '/admin/setup': typeof AdminSetupRoute
  '/api/debug-fetch-emails': typeof ApiDebugFetchEmailsRoute
  '/api/debug-gmail-token': typeof ApiDebugGmailTokenRoute
  '/api/debug-interpret-email': typeof ApiDebugInterpretEmailRoute
  '/api/debug-process-email': typeof ApiDebugProcessEmailRoute
  '/api/debug-process-pipeline': typeof ApiDebugProcessPipelineRoute
  '/api/delete-gmail-token': typeof ApiDeleteGmailTokenRoute
  '/api/gmail-callback': typeof ApiGmailCallbackRoute
  '/api/gmail-webhook': typeof ApiGmailWebhookRoute
  '/api/version': typeof ApiVersionRoute
  '/api/whatsapp-webhook': typeof ApiWhatsappWebhookRoute
  '/config/permissions': typeof ConfigPermissionsRoute
  '/crm/chamados': typeof CrmChamadosRouteWithChildren
  '/crm/clientes': typeof CrmClientesRouteWithChildren
  '/crm/contratos': typeof CrmContratosRouteWithChildren
  '/crm/orcamentos': typeof CrmOrcamentosRouteWithChildren
  '/crm/os': typeof CrmOsRouteWithChildren
  '/crm/pagamentos': typeof CrmPagamentosRoute
  '/crm/pecas': typeof CrmPecasRoute
  '/crm/pipeline': typeof CrmPipelineRoute
  '/crm/servicos': typeof CrmServicosRoute
  '/crm/tarefas': typeof CrmTarefasRoute
  '/ferramentas/emails': typeof FerramentasEmailsRoute
  '/ferramentas/excel': typeof FerramentasExcelRoute
  '/ferramentas/whatsapp': typeof FerramentasWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/config/': typeof ConfigIndexRoute
  '/ferramentas/': typeof FerramentasIndexRoute
  '/crm/chamados/$id': typeof CrmChamadosIdRoute
  '/crm/clientes/$id': typeof CrmClientesIdRoute
  '/crm/contratos/modelos': typeof CrmContratosModelosRoute
  '/crm/contratos/novo': typeof CrmContratosNovoRoute
  '/crm/orcamentos/$id': typeof CrmOrcamentosIdRoute
  '/orcamento/approve/$token': typeof OrcamentoApproveTokenRoute
  '/crm/chamados/': typeof CrmChamadosIndexRoute
  '/crm/clientes/': typeof CrmClientesIndexRoute
  '/crm/contratos/': typeof CrmContratosIndexRoute
  '/crm/orcamentos/': typeof CrmOrcamentosIndexRoute
  '/crm/os/': typeof CrmOsIndexRoute
  '/crm/orcamentos/editar/$id': typeof CrmOrcamentosEditarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/agenda'
    | '/anotacoes'
    | '/arquivos'
    | '/config'
    | '/crm'
    | '/dashboard'
    | '/debug-user-id'
    | '/ferramentas'
    | '/login'
    | '/projetos'
    | '/admin/$operatorId'
    | '/admin/setup'
    | '/api/debug-fetch-emails'
    | '/api/debug-gmail-token'
    | '/api/debug-interpret-email'
    | '/api/debug-process-email'
    | '/api/debug-process-pipeline'
    | '/api/delete-gmail-token'
    | '/api/gmail-callback'
    | '/api/gmail-webhook'
    | '/api/version'
    | '/api/whatsapp-webhook'
    | '/config/permissions'
    | '/crm/chamados'
    | '/crm/clientes'
    | '/crm/contratos'
    | '/crm/orcamentos'
    | '/crm/os'
    | '/crm/pagamentos'
    | '/crm/pecas'
    | '/crm/pipeline'
    | '/crm/servicos'
    | '/crm/tarefas'
    | '/ferramentas/emails'
    | '/ferramentas/excel'
    | '/ferramentas/whatsapp'
    | '/admin/'
    | '/config/'
    | '/ferramentas/'
    | '/crm/chamados/$id'
    | '/crm/clientes/$id'
    | '/crm/contratos/modelos'
    | '/crm/contratos/novo'
    | '/crm/orcamentos/$id'
    | '/orcamento/approve/$token'
    | '/crm/chamados/'
    | '/crm/clientes/'
    | '/crm/contratos/'
    | '/crm/orcamentos/'
    | '/crm/os/'
    | '/crm/orcamentos/editar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agenda'
    | '/anotacoes'
    | '/arquivos'
    | '/crm'
    | '/dashboard'
    | '/debug-user-id'
    | '/login'
    | '/projetos'
    | '/admin/$operatorId'
    | '/admin/setup'
    | '/api/debug-fetch-emails'
    | '/api/debug-gmail-token'
    | '/api/debug-interpret-email'
    | '/api/debug-process-email'
    | '/api/debug-process-pipeline'
    | '/api/delete-gmail-token'
    | '/api/gmail-callback'
    | '/api/gmail-webhook'
    | '/api/version'
    | '/api/whatsapp-webhook'
    | '/config/permissions'
    | '/crm/pagamentos'
    | '/crm/pecas'
    | '/crm/pipeline'
    | '/crm/servicos'
    | '/crm/tarefas'
    | '/ferramentas/emails'
    | '/ferramentas/excel'
    | '/ferramentas/whatsapp'
    | '/admin'
    | '/config'
    | '/ferramentas'
    | '/crm/chamados/$id'
    | '/crm/clientes/$id'
    | '/crm/contratos/modelos'
    | '/crm/contratos/novo'
    | '/crm/orcamentos/$id'
    | '/orcamento/approve/$token'
    | '/crm/chamados'
    | '/crm/clientes'
    | '/crm/contratos'
    | '/crm/orcamentos'
    | '/crm/os'
    | '/crm/orcamentos/editar/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/agenda'
    | '/anotacoes'
    | '/arquivos'
    | '/config'
    | '/crm'
    | '/dashboard'
    | '/debug-user-id'
    | '/ferramentas'
    | '/login'
    | '/projetos'
    | '/admin/$operatorId'
    | '/admin/setup'
    | '/api/debug-fetch-emails'
    | '/api/debug-gmail-token'
    | '/api/debug-interpret-email'
    | '/api/debug-process-email'
    | '/api/debug-process-pipeline'
    | '/api/delete-gmail-token'
    | '/api/gmail-callback'
    | '/api/gmail-webhook'
    | '/api/version'
    | '/api/whatsapp-webhook'
    | '/config/permissions'
    | '/crm/chamados'
    | '/crm/clientes'
    | '/crm/contratos'
    | '/crm/orcamentos'
    | '/crm/os'
    | '/crm/pagamentos'
    | '/crm/pecas'
    | '/crm/pipeline'
    | '/crm/servicos'
    | '/crm/tarefas'
    | '/ferramentas/emails'
    | '/ferramentas/excel'
    | '/ferramentas/whatsapp'
    | '/admin/'
    | '/config/'
    | '/ferramentas/'
    | '/crm/chamados/$id'
    | '/crm/clientes/$id'
    | '/crm/contratos/modelos'
    | '/crm/contratos/novo'
    | '/crm/orcamentos/$id'
    | '/orcamento/approve/$token'
    | '/crm/chamados/'
    | '/crm/clientes/'
    | '/crm/contratos/'
    | '/crm/orcamentos/'
    | '/crm/os/'
    | '/crm/orcamentos/editar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AgendaRoute: typeof AgendaRoute
  AnotacoesRoute: typeof AnotacoesRoute
  ArquivosRoute: typeof ArquivosRoute
  ConfigRoute: typeof ConfigRouteWithChildren
  CrmRoute: typeof CrmRouteWithChildren
  DashboardRoute: typeof DashboardRoute
  DebugUserIdRoute: typeof DebugUserIdRoute
  FerramentasRoute: typeof FerramentasRouteWithChildren
  LoginRoute: typeof LoginRoute
  ProjetosRoute: typeof ProjetosRoute
  ApiDebugFetchEmailsRoute: typeof ApiDebugFetchEmailsRoute
  ApiDebugGmailTokenRoute: typeof ApiDebugGmailTokenRoute
  ApiDebugInterpretEmailRoute: typeof ApiDebugInterpretEmailRoute
  ApiDebugProcessEmailRoute: typeof ApiDebugProcessEmailRoute
  ApiDebugProcessPipelineRoute: typeof ApiDebugProcessPipelineRoute
  ApiDeleteGmailTokenRoute: typeof ApiDeleteGmailTokenRoute
  ApiGmailCallbackRoute: typeof ApiGmailCallbackRoute
  ApiGmailWebhookRoute: typeof ApiGmailWebhookRoute
  ApiVersionRoute: typeof ApiVersionRoute
  ApiWhatsappWebhookRoute: typeof ApiWhatsappWebhookRoute
  OrcamentoApproveTokenRoute: typeof OrcamentoApproveTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas': {
      id: '/ferramentas'
      path: '/ferramentas'
      fullPath: '/ferramentas'
      preLoaderRoute: typeof FerramentasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug-user-id': {
      id: '/debug-user-id'
      path: '/debug-user-id'
      fullPath: '/debug-user-id'
      preLoaderRoute: typeof DebugUserIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm': {
      id: '/crm'
      path: '/crm'
      fullPath: '/crm'
      preLoaderRoute: typeof CrmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/config': {
      id: '/config'
      path: '/config'
      fullPath: '/config'
      preLoaderRoute: typeof ConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/arquivos': {
      id: '/arquivos'
      path: '/arquivos'
      fullPath: '/arquivos'
      preLoaderRoute: typeof ArquivosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anotacoes': {
      id: '/anotacoes'
      path: '/anotacoes'
      fullPath: '/anotacoes'
      preLoaderRoute: typeof AnotacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda': {
      id: '/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AgendaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ferramentas/': {
      id: '/ferramentas/'
      path: '/'
      fullPath: '/ferramentas/'
      preLoaderRoute: typeof FerramentasIndexRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/config/': {
      id: '/config/'
      path: '/'
      fullPath: '/config/'
      preLoaderRoute: typeof ConfigIndexRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/ferramentas/whatsapp': {
      id: '/ferramentas/whatsapp'
      path: '/whatsapp'
      fullPath: '/ferramentas/whatsapp'
      preLoaderRoute: typeof FerramentasWhatsappRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/excel': {
      id: '/ferramentas/excel'
      path: '/excel'
      fullPath: '/ferramentas/excel'
      preLoaderRoute: typeof FerramentasExcelRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/ferramentas/emails': {
      id: '/ferramentas/emails'
      path: '/emails'
      fullPath: '/ferramentas/emails'
      preLoaderRoute: typeof FerramentasEmailsRouteImport
      parentRoute: typeof FerramentasRoute
    }
    '/crm/tarefas': {
      id: '/crm/tarefas'
      path: '/tarefas'
      fullPath: '/crm/tarefas'
      preLoaderRoute: typeof CrmTarefasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/servicos': {
      id: '/crm/servicos'
      path: '/servicos'
      fullPath: '/crm/servicos'
      preLoaderRoute: typeof CrmServicosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pipeline': {
      id: '/crm/pipeline'
      path: '/pipeline'
      fullPath: '/crm/pipeline'
      preLoaderRoute: typeof CrmPipelineRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pecas': {
      id: '/crm/pecas'
      path: '/pecas'
      fullPath: '/crm/pecas'
      preLoaderRoute: typeof CrmPecasRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/pagamentos': {
      id: '/crm/pagamentos'
      path: '/pagamentos'
      fullPath: '/crm/pagamentos'
      preLoaderRoute: typeof CrmPagamentosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/os': {
      id: '/crm/os'
      path: '/os'
      fullPath: '/crm/os'
      preLoaderRoute: typeof CrmOsRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/orcamentos': {
      id: '/crm/orcamentos'
      path: '/orcamentos'
      fullPath: '/crm/orcamentos'
      preLoaderRoute: typeof CrmOrcamentosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/contratos': {
      id: '/crm/contratos'
      path: '/contratos'
      fullPath: '/crm/contratos'
      preLoaderRoute: typeof CrmContratosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/clientes': {
      id: '/crm/clientes'
      path: '/clientes'
      fullPath: '/crm/clientes'
      preLoaderRoute: typeof CrmClientesRouteImport
      parentRoute: typeof CrmRoute
    }
    '/crm/chamados': {
      id: '/crm/chamados'
      path: '/chamados'
      fullPath: '/crm/chamados'
      preLoaderRoute: typeof CrmChamadosRouteImport
      parentRoute: typeof CrmRoute
    }
    '/config/permissions': {
      id: '/config/permissions'
      path: '/permissions'
      fullPath: '/config/permissions'
      preLoaderRoute: typeof ConfigPermissionsRouteImport
      parentRoute: typeof ConfigRoute
    }
    '/api/whatsapp-webhook': {
      id: '/api/whatsapp-webhook'
      path: '/api/whatsapp-webhook'
      fullPath: '/api/whatsapp-webhook'
      preLoaderRoute: typeof ApiWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/version': {
      id: '/api/version'
      path: '/api/version'
      fullPath: '/api/version'
      preLoaderRoute: typeof ApiVersionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-webhook': {
      id: '/api/gmail-webhook'
      path: '/api/gmail-webhook'
      fullPath: '/api/gmail-webhook'
      preLoaderRoute: typeof ApiGmailWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/gmail-callback': {
      id: '/api/gmail-callback'
      path: '/api/gmail-callback'
      fullPath: '/api/gmail-callback'
      preLoaderRoute: typeof ApiGmailCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/delete-gmail-token': {
      id: '/api/delete-gmail-token'
      path: '/api/delete-gmail-token'
      fullPath: '/api/delete-gmail-token'
      preLoaderRoute: typeof ApiDeleteGmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-process-pipeline': {
      id: '/api/debug-process-pipeline'
      path: '/api/debug-process-pipeline'
      fullPath: '/api/debug-process-pipeline'
      preLoaderRoute: typeof ApiDebugProcessPipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-process-email': {
      id: '/api/debug-process-email'
      path: '/api/debug-process-email'
      fullPath: '/api/debug-process-email'
      preLoaderRoute: typeof ApiDebugProcessEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-interpret-email': {
      id: '/api/debug-interpret-email'
      path: '/api/debug-interpret-email'
      fullPath: '/api/debug-interpret-email'
      preLoaderRoute: typeof ApiDebugInterpretEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-gmail-token': {
      id: '/api/debug-gmail-token'
      path: '/api/debug-gmail-token'
      fullPath: '/api/debug-gmail-token'
      preLoaderRoute: typeof ApiDebugGmailTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/debug-fetch-emails': {
      id: '/api/debug-fetch-emails'
      path: '/api/debug-fetch-emails'
      fullPath: '/api/debug-fetch-emails'
      preLoaderRoute: typeof ApiDebugFetchEmailsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/setup': {
      id: '/admin/setup'
      path: '/setup'
      fullPath: '/admin/setup'
      preLoaderRoute: typeof AdminSetupRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/$operatorId': {
      id: '/admin/$operatorId'
      path: '/$operatorId'
      fullPath: '/admin/$operatorId'
      preLoaderRoute: typeof AdminOperatorIdRouteImport
      parentRoute: typeof AdminRoute
    }
    '/crm/os/': {
      id: '/crm/os/'
      path: '/'
      fullPath: '/crm/os/'
      preLoaderRoute: typeof CrmOsIndexRouteImport
      parentRoute: typeof CrmOsRoute
    }
    '/crm/orcamentos/': {
      id: '/crm/orcamentos/'
      path: '/'
      fullPath: '/crm/orcamentos/'
      preLoaderRoute: typeof CrmOrcamentosIndexRouteImport
      parentRoute: typeof CrmOrcamentosRoute
    }
    '/crm/contratos/': {
      id: '/crm/contratos/'
      path: '/'
      fullPath: '/crm/contratos/'
      preLoaderRoute: typeof CrmContratosIndexRouteImport
      parentRoute: typeof CrmContratosRoute
    }
    '/crm/clientes/': {
      id: '/crm/clientes/'
      path: '/'
      fullPath: '/crm/clientes/'
      preLoaderRoute: typeof CrmClientesIndexRouteImport
      parentRoute: typeof CrmClientesRoute
    }
    '/crm/chamados/': {
      id: '/crm/chamados/'
      path: '/'
      fullPath: '/crm/chamados/'
      preLoaderRoute: typeof CrmChamadosIndexRouteImport
      parentRoute: typeof CrmChamadosRoute
    }
    '/orcamento/approve/$token': {
      id: '/orcamento/approve/$token'
      path: '/orcamento/approve/$token'
      fullPath: '/orcamento/approve/$token'
      preLoaderRoute: typeof OrcamentoApproveTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/crm/orcamentos/$id': {
      id: '/crm/orcamentos/$id'
      path: '/$id'
      fullPath: '/crm/orcamentos/$id'
      preLoaderRoute: typeof CrmOrcamentosIdRouteImport
      parentRoute: typeof CrmOrcamentosRoute
    }
    '/crm/contratos/novo': {
      id: '/crm/contratos/novo'
      path: '/novo'
      fullPath: '/crm/contratos/novo'
      preLoaderRoute: typeof CrmContratosNovoRouteImport
      parentRoute: typeof CrmContratosRoute
    }
    '/crm/contratos/modelos': {
      id: '/crm/contratos/modelos'
      path: '/modelos'
      fullPath: '/crm/contratos/modelos'
      preLoaderRoute: typeof CrmContratosModelosRouteImport
      parentRoute: typeof CrmContratosRoute
    }
    '/crm/clientes/$id': {
      id: '/crm/clientes/$id'
      path: '/$id'
      fullPath: '/crm/clientes/$id'
      preLoaderRoute: typeof CrmClientesIdRouteImport
      parentRoute: typeof CrmClientesRoute
    }
    '/crm/chamados/$id': {
      id: '/crm/chamados/$id'
      path: '/$id'
      fullPath: '/crm/chamados/$id'
      preLoaderRoute: typeof CrmChamadosIdRouteImport
      parentRoute: typeof CrmChamadosRoute
    }
    '/crm/orcamentos/editar/$id': {
      id: '/crm/orcamentos/editar/$id'
      path: '/editar/$id'
      fullPath: '/crm/orcamentos/editar/$id'
      preLoaderRoute: typeof CrmOrcamentosEditarIdRouteImport
      parentRoute: typeof CrmOrcamentosRoute
    }
  }
}

interface AdminRouteChildren {
  AdminOperatorIdRoute: typeof AdminOperatorIdRoute
  AdminSetupRoute: typeof AdminSetupRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminOperatorIdRoute: AdminOperatorIdRoute,
  AdminSetupRoute: AdminSetupRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ConfigRouteChildren {
  ConfigPermissionsRoute: typeof ConfigPermissionsRoute
  ConfigIndexRoute: typeof ConfigIndexRoute
}

const ConfigRouteChildren: ConfigRouteChildren = {
  ConfigPermissionsRoute: ConfigPermissionsRoute,
  ConfigIndexRoute: ConfigIndexRoute,
}

const ConfigRouteWithChildren =
  ConfigRoute._addFileChildren(ConfigRouteChildren)

interface CrmChamadosRouteChildren {
  CrmChamadosIdRoute: typeof CrmChamadosIdRoute
  CrmChamadosIndexRoute: typeof CrmChamadosIndexRoute
}

const CrmChamadosRouteChildren: CrmChamadosRouteChildren = {
  CrmChamadosIdRoute: CrmChamadosIdRoute,
  CrmChamadosIndexRoute: CrmChamadosIndexRoute,
}

const CrmChamadosRouteWithChildren = CrmChamadosRoute._addFileChildren(
  CrmChamadosRouteChildren,
)

interface CrmClientesRouteChildren {
  CrmClientesIdRoute: typeof CrmClientesIdRoute
  CrmClientesIndexRoute: typeof CrmClientesIndexRoute
}

const CrmClientesRouteChildren: CrmClientesRouteChildren = {
  CrmClientesIdRoute: CrmClientesIdRoute,
  CrmClientesIndexRoute: CrmClientesIndexRoute,
}

const CrmClientesRouteWithChildren = CrmClientesRoute._addFileChildren(
  CrmClientesRouteChildren,
)

interface CrmContratosRouteChildren {
  CrmContratosModelosRoute: typeof CrmContratosModelosRoute
  CrmContratosNovoRoute: typeof CrmContratosNovoRoute
  CrmContratosIndexRoute: typeof CrmContratosIndexRoute
}

const CrmContratosRouteChildren: CrmContratosRouteChildren = {
  CrmContratosModelosRoute: CrmContratosModelosRoute,
  CrmContratosNovoRoute: CrmContratosNovoRoute,
  CrmContratosIndexRoute: CrmContratosIndexRoute,
}

const CrmContratosRouteWithChildren = CrmContratosRoute._addFileChildren(
  CrmContratosRouteChildren,
)

interface CrmOrcamentosRouteChildren {
  CrmOrcamentosIdRoute: typeof CrmOrcamentosIdRoute
  CrmOrcamentosIndexRoute: typeof CrmOrcamentosIndexRoute
  CrmOrcamentosEditarIdRoute: typeof CrmOrcamentosEditarIdRoute
}

const CrmOrcamentosRouteChildren: CrmOrcamentosRouteChildren = {
  CrmOrcamentosIdRoute: CrmOrcamentosIdRoute,
  CrmOrcamentosIndexRoute: CrmOrcamentosIndexRoute,
  CrmOrcamentosEditarIdRoute: CrmOrcamentosEditarIdRoute,
}

const CrmOrcamentosRouteWithChildren = CrmOrcamentosRoute._addFileChildren(
  CrmOrcamentosRouteChildren,
)

interface CrmOsRouteChildren {
  CrmOsIndexRoute: typeof CrmOsIndexRoute
}

const CrmOsRouteChildren: CrmOsRouteChildren = {
  CrmOsIndexRoute: CrmOsIndexRoute,
}

const CrmOsRouteWithChildren = CrmOsRoute._addFileChildren(CrmOsRouteChildren)

interface CrmRouteChildren {
  CrmChamadosRoute: typeof CrmChamadosRouteWithChildren
  CrmClientesRoute: typeof CrmClientesRouteWithChildren
  CrmContratosRoute: typeof CrmContratosRouteWithChildren
  CrmOrcamentosRoute: typeof CrmOrcamentosRouteWithChildren
  CrmOsRoute: typeof CrmOsRouteWithChildren
  CrmPagamentosRoute: typeof CrmPagamentosRoute
  CrmPecasRoute: typeof CrmPecasRoute
  CrmPipelineRoute: typeof CrmPipelineRoute
  CrmServicosRoute: typeof CrmServicosRoute
  CrmTarefasRoute: typeof CrmTarefasRoute
}

const CrmRouteChildren: CrmRouteChildren = {
  CrmChamadosRoute: CrmChamadosRouteWithChildren,
  CrmClientesRoute: CrmClientesRouteWithChildren,
  CrmContratosRoute: CrmContratosRouteWithChildren,
  CrmOrcamentosRoute: CrmOrcamentosRouteWithChildren,
  CrmOsRoute: CrmOsRouteWithChildren,
  CrmPagamentosRoute: CrmPagamentosRoute,
  CrmPecasRoute: CrmPecasRoute,
  CrmPipelineRoute: CrmPipelineRoute,
  CrmServicosRoute: CrmServicosRoute,
  CrmTarefasRoute: CrmTarefasRoute,
}

const CrmRouteWithChildren = CrmRoute._addFileChildren(CrmRouteChildren)

interface FerramentasRouteChildren {
  FerramentasEmailsRoute: typeof FerramentasEmailsRoute
  FerramentasExcelRoute: typeof FerramentasExcelRoute
  FerramentasWhatsappRoute: typeof FerramentasWhatsappRoute
  FerramentasIndexRoute: typeof FerramentasIndexRoute
}

const FerramentasRouteChildren: FerramentasRouteChildren = {
  FerramentasEmailsRoute: FerramentasEmailsRoute,
  FerramentasExcelRoute: FerramentasExcelRoute,
  FerramentasWhatsappRoute: FerramentasWhatsappRoute,
  FerramentasIndexRoute: FerramentasIndexRoute,
}

const FerramentasRouteWithChildren = FerramentasRoute._addFileChildren(
  FerramentasRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AgendaRoute: AgendaRoute,
  AnotacoesRoute: AnotacoesRoute,
  ArquivosRoute: ArquivosRoute,
  ConfigRoute: ConfigRouteWithChildren,
  CrmRoute: CrmRouteWithChildren,
  DashboardRoute: DashboardRoute,
  DebugUserIdRoute: DebugUserIdRoute,
  FerramentasRoute: FerramentasRouteWithChildren,
  LoginRoute: LoginRoute,
  ProjetosRoute: ProjetosRoute,
  ApiDebugFetchEmailsRoute: ApiDebugFetchEmailsRoute,
  ApiDebugGmailTokenRoute: ApiDebugGmailTokenRoute,
  ApiDebugInterpretEmailRoute: ApiDebugInterpretEmailRoute,
  ApiDebugProcessEmailRoute: ApiDebugProcessEmailRoute,
  ApiDebugProcessPipelineRoute: ApiDebugProcessPipelineRoute,
  ApiDeleteGmailTokenRoute: ApiDeleteGmailTokenRoute,
  ApiGmailCallbackRoute: ApiGmailCallbackRoute,
  ApiGmailWebhookRoute: ApiGmailWebhookRoute,
  ApiVersionRoute: ApiVersionRoute,
  ApiWhatsappWebhookRoute: ApiWhatsappWebhookRoute,
  OrcamentoApproveTokenRoute: OrcamentoApproveTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
